Models/Appointment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClinicAppointmentClient.Models
{
    public class Appointment
    {
        public int Id { get; set; }
        public string PatientName { get; set; }
        public string PhoneNumber { get; set; }
        public int? DoctorId { get; set; }
        public DateTime Date { get; set; }
        public int? TimeSlotId { get; set; }
        public bool IsLate { get; set; }
        public bool NoShow { get; set; }

        // Navigation
        public Doctor Doctor { get; set; }
        public TimeSlot TimeSlot { get; set; }
    }
}

Controllers/AppointmentController.cs
using ClinicAppointmentClient.Models;
using ClinicAppointmentClient.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text;

namespace ClinicAppointmentClient.Controllers
{
    public class AppointmentController : Controller
    {
        const string API_URL = "https://localhost:7182/api";

        Uri baseAddress = new Uri(API_URL);
        private readonly HttpClient _client;

        public AppointmentController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }

        [HttpGet]
        public IActionResult Index(string term, int currentPage = 1)
        {
            var response = _client.GetAsync($"{_client.BaseAddress}/appointment").Result;
            string data = response.Content.ReadAsStringAsync().Result;
            var billList = JsonConvert.DeserializeObject<List<Appointment>>(data);

            var totalRecords = billList.Count(); // Set the total amount of records
            var pageSize = 5; // Set the page size
            var totalPages = (int)Math.Ceiling(totalRecords / (double)pageSize);

            var obj = new AppointmentVM
            {
                Data = billList.AsQueryable(),
                CurrentPage = currentPage,
                PageSize = pageSize,
                TotalPages = totalPages,
                term = term,
            };

            if (String.IsNullOrEmpty(term))
            {
                obj.Data = billList.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList().AsQueryable();
                return View(obj);
            }
            else
            {
                term = term.ToLower();
                var searchedItems = obj.Data.Where(s => s.PatientName.ToLower().Contains(term)).ToList();

                var totalRecords2 = searchedItems.Count(); // Set the total amount of records
                obj.TotalPages = (int)Math.Ceiling(totalRecords2 / (double)obj.PageSize);
                obj.CurrentPage = currentPage;

                // Apply pagination to the filtered results
                searchedItems = searchedItems.Skip((currentPage - 1) * obj.PageSize).Take(obj.PageSize).ToList();

                obj.Data = searchedItems.AsQueryable();

                return View(obj);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Pull API data for washers
            var doctorResponse = _client.GetAsync($"{_client.BaseAddress}/doctor").Result;
            var doctorData = doctorResponse.Content.ReadAsStringAsync().Result;
            List<Doctor> doctorList = JsonConvert.DeserializeObject<List<Doctor>>(doctorData)!;

            // Pull API data for vehicle
            var timeslotResponse = _client.GetAsync($"{_client.BaseAddress}/timeslot").Result;
            var timeslotData = timeslotResponse.Content.ReadAsStringAsync().Result;
            List<TimeSlot> timeslotList = JsonConvert.DeserializeObject<List<TimeSlot>>(timeslotData)!;

            // To prevent issues, if a washer is not avail then 
            // they will not be displayed in the dropdown list
            var doctors = doctorList.AsQueryable();
            var availDoctors = doctors.Where(s => s.IsAvailable == true).ToList();


            // Bind properties to the dropdown list
            var viewModel = new AppointmentVM
            {
                DoctorLists = availDoctors.Select(doc => new SelectListItem
                {
                    Text = doc.DoctorName,
                    Value = doc.Id.ToString()
                }).ToList(),
                TimeSlotLists = timeslotList.Select(ts => new SelectListItem
                {
                    Text = ts.Slot,
                    Value = ts.Id.ToString()
                }).ToList(),
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(AppointmentVM vm)
        {
            //if (!ModelState.IsValid) return View(vm); //commented out because it wouldnt let my code run
            //ran perfectly without it

            // Save the selected item from dropdown 
            // And textbox entry to the bill object
            var appt = new Appointment
            {
                PatientName = vm.PatientName,
                PhoneNumber = vm.PhoneNumber,
                DoctorId = (int)vm.SelectedDoctorId,
                Date = vm.Date,
                TimeSlotId = (int)vm.SelectedTimeSlotId,
                IsLate = vm.IsLate,
                NoShow = vm.NoShow,
            };

            // check if this doctor is already booked on that date at that time 
            //var availResponse = _client.GetAsync($"{_client.BaseAddress/})

            // Pull data from api for washer and set washer to not available if they are booked
            var docGetResponse = _client.GetAsync($"{_client.BaseAddress}/doctor/{appt.DoctorId}").Result;
            var docGetData = docGetResponse.Content.ReadAsStringAsync().Result;
            var selectedDoc = JsonConvert.DeserializeObject<Doctor>(docGetData);

            selectedDoc.IsAvailable = false;

            string docPutData = JsonConvert.SerializeObject(selectedDoc);
            StringContent docContent = new StringContent(docPutData, Encoding.UTF8, "application/json");
            HttpResponseMessage docPutResponse = _client.PutAsync($"{_client.BaseAddress}/washer/{appt.DoctorId}", docContent).Result;



            // Serialize the object and sends it to thru the API to the DB
            var data = JsonConvert.SerializeObject(appt);
            StringContent content = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
            var response = _client.PostAsync($"{_client.BaseAddress}/appointment", content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(vm);
            }
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            //Get appt record using Id and deserialize it in a variable
            var response = _client.GetAsync($"{_client.BaseAddress}/appointment/{Id}").Result;
            var content = response.Content.ReadAsStringAsync().Result;
            var appt = JsonConvert.DeserializeObject<Appointment>(content);

            // Pull API data for doctors
            var doctorResponse = _client.GetAsync($"{_client.BaseAddress}/doctor").Result;
            var doctorData = doctorResponse.Content.ReadAsStringAsync().Result;
            List<Doctor> docList = JsonConvert.DeserializeObject<List<Doctor>>(doctorData)!;

            // Pull API data for timeslot
            var timeslotResponse = _client.GetAsync($"{_client.BaseAddress}/timeslot").Result;
            var timeslotData = timeslotResponse.Content.ReadAsStringAsync().Result;
            List<TimeSlot> timeslotList = JsonConvert.DeserializeObject<List<TimeSlot>>(timeslotData)!;

            // To prevent issues, if a washer is not avail then 
            // they will not be displayed in the dropdown list
            var doctors = docList.AsQueryable();
            var availDoctors = doctors.Where(s => s.IsAvailable == true).ToList();

            var viewModel = new AppointmentVM
            {
                PatientName = appt.PatientName,
                PhoneNumber = appt.PhoneNumber,
                SelectedDoctorId = (int)appt.DoctorId,
                Date = appt.Date,
                SelectedTimeSlotId = (int)appt.TimeSlotId,
                IsLate = appt.IsLate,
                NoShow = appt.NoShow,

                DoctorLists = availDoctors.Select(doc => new SelectListItem
                {
                    Text = doc.DoctorName,
                    Value = doc.Id.ToString()
                }).ToList(),
                TimeSlotLists = timeslotList.Select(ts => new SelectListItem
                {
                    Text = ts.Slot,
                    Value = ts.Id.ToString()
                }).ToList(),
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(AppointmentVM vm)
        {
            //if (!ModelState.IsValid) return View(vm);

            var appt = new Appointment
            {
                Id = vm.Id,
                PatientName = vm.PatientName,
                PhoneNumber = vm.PhoneNumber,
                DoctorId = (int)vm.SelectedDoctorId,
                Date = vm.Date,
                TimeSlotId = (int)vm.SelectedTimeSlotId,
                IsLate = vm.IsLate,
                NoShow = vm.NoShow,
            };

            var data = JsonConvert.SerializeObject(appt);
            StringContent content = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
            var response = _client.PutAsync($"{_client.BaseAddress}/appointment/{appt.Id}", content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(vm);
            }
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            try
            {
                Appointment appt = new Appointment();

                HttpResponseMessage response = _client.GetAsync($"{_client.BaseAddress}/appointment/{Id}").Result;

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    appt = JsonConvert.DeserializeObject<Appointment>(data);
                }
                return View(appt);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int Id)
        {

Views/Appointment/Create.cshtml
@model ClinicAppointmentClient.Models.ViewModels.AppointmentVM

@{
    ViewData["Title"] = "Book Appointment";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h4 class="text-center text-white">Book Appointment</h4>
            <hr style="color: white;"/>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="PatientName" class="control-label text-white">Patient Name</label>
                    <input asp-for="PatientName" class="form-control" />
                    <span asp-validation-for="PatientName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label text-white">Phone Number</label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label text-white">Appointment Date</label>
                    <input asp-for="Date" type="date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SelectedDoctorId" class="control-label text-white">Select Doctor</label>
                    <select asp-for="SelectedDoctorId" asp-items="@Model.DoctorLists" class="form-control">
                        <option disabled selected>Select Doctor</option>
                    </select>
                    <span asp-validation-for="SelectedDoctorId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SelectedTimeSlotId" class="control-label text-white">Select Timeslot</label>
                    <select asp-for="SelectedTimeSlotId" asp-items="@Model.TimeSlotLists" class="form-control">
                        <option disabled selected>Select Timeslot</option>
                    </select>
                    <span asp-validation-for="SelectedTimeSlotId" class="text-danger"></span>
                </div>
                <div class="form-group mt-4 text-center">
                    <a asp-action="Index" class="btn btn-outline-warning ml-2">
                        <i class="fa-solid fa-arrow-left"></i> Back
                    </a>
                    <button type="submit" class="btn btn-primary ml-2">
                        <i class="fa-regular fa-floppy-disk"></i>
                        Create
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Appointment/Delete.cshtml
@model ClinicAppointmentClient.Models.Appointment

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h3 class="text-center text-white">Are you sure you want to delete this?</h3>
            <div>
                <hr style="color: white;" />
                <dl class="row">
                    <dt class="col-sm-2 text-white">
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd class="col-sm-10 text-white">
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                    <dt class="col-sm-2 text-white">
                        Patient Name
                    </dt>
                    <dd class="col-sm-10 text-white">
                        @Html.DisplayFor(model => model.PatientName)
                    </dd>
                    <dt class="col-sm-2 text-white">
                        Phone Number
                    </dt>
                    <dd class="col-sm-10 text-white">
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>
                    <dt class="col-sm-2 text-white">
                        Doctor Assigned
                    </dt>
                    <dd class="col-sm-10 text-white">
                        @Html.DisplayFor(model => model.Doctor.DoctorName)
                    </dd>
                    <dt class="col-sm-2 text-white">
                        @Html.DisplayNameFor(model => model.Date)
                    </dt>
                    <dd class="col-sm-10 text-white" ">
                    @Html.DisplayFor(model => model.Date)
                    </dd>
                    <dt class="col-sm-2 text-white">
                        Time Slot
                    </dt>
                    <dd class="col-sm-10 text-white">
                    @Html.DisplayFor(model => model.TimeSlot.Slot)
                    </dd>
                    <dt class="col-sm-2 text-white">
                        Late
                    </dt>
                    <dd class="col-sm-10 text-white">
                    @Html.DisplayFor(model => model.IsLate)
                    </dd>
                </dl>
                <div>
                    <form asp-action="Delete" class="mt-4 text-center">
                        <a asp-action="Index" class="btn btn-secondary">
                            <i class="fa-solid fa-arrow-left"></i>Back
                        </a>
                        <div>
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Appointment/Edit.cshtml
@model ClinicAppointmentClient.Models.ViewModels.AppointmentVM

@{
    ViewData["Title"] = "Edit Appointment Info";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h4 class="text-center text-white">Edit Appointment</h4>
            <hr />
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="PatientName" class="control-label text-white">Patient Name</label>
                    <input asp-for="PatientName" class="form-control" />
                    <span asp-validation-for="PatientName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label text-white">Phone Number</label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label text-white">Appointment Date</label>
                    <input asp-for="Date" type="date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SelectedDoctorId" class="control-label text-white">Select Doctor</label>
                    <select asp-for="SelectedDoctorId" asp-items="@Model.DoctorLists" class="form-control">
                        <option disabled selected>Select Doctor</option>
                    </select>
                    <span asp-validation-for="SelectedDoctorId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SelectedTimeSlotId" class="control-label text-white">Select Timeslot</label>
                    <select asp-for="SelectedTimeSlotId" asp-items="@Model.TimeSlotLists" class="form-control">
                        <option disabled selected>Select Timeslot</option>
                    </select>
                    <span asp-validation-for="SelectedTimeSlotId" class="text-danger"></span>
                </div>
                <div class="form-group mt-4 text-center">
                    <a asp-action="Index" class="btn btn-outline-warning ml-2">
                        <i class="fa-solid fa-arrow-left"></i> Back
                    </a>
                    <button type="submit" class="btn btn-primary ml-2">
                        <i class="fa-regular fa-floppy-disk"></i>
                        Save
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Appointment/Index.cshtml
@model ClinicAppointmentClient.Models.ViewModels.AppointmentVM

@{
    ViewData["Title"] = "Appointment List";
}

<div style="padding-top: 30px;">
    <h1>List of Appointments</h1>
    <form asp-action="Index" method="get" class="pb-2">
        <div class="input-group md-form form-sm form-2 pl-0">
            <input name="term" class="form-control my-0 py-1 red-border" type="text" placeholder="Search" />
                <span class="input-group-text red lighten-3" id="basic-text1">
                    <i class="fas fa-search text-grey" aria-hidden="true"></i>
                </span>
        </div>
    </form>
    <table class="table table-hover table-striped bg-white rounded">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    Patient
                </th>
                <th>
                    Patient Number
                </th>
                <th>
                    Doctor Assigned
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    Time Slot
                </th>
                <th>
                    Late
                </th>
                <th>
                    No Show
                </th>
                <th>
                    <a asp-action="Create" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-plus"></i></a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Doctor.DoctorName)
                    </td>
                    <td>
                        @if (item.Date < DateTime.Today)
                        {
                            <p>
                                @item.Date.ToString("dddd, MMM d")
                                <a class="btn btn-sm btn-warning disabled">
                                    PAST
                                </a>
                            </p>
                        }
                        else if (item.Date == DateTime.Today)
                        {
                            <p>
                                @item.Date.ToString("dddd, MMM d")
                                <a class="btn btn-sm btn-success disabled">
                                    TODAY
                                </a>
                            </p>
                        }
                        else if (item.Date > DateTime.Today)
                        {
                            <p>
                                @item.Date.ToString("dddd, MMM d")
                                <a class="btn btn-sm btn-info disabled">
                                    UPCOMING
                                </a>
                            </p>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeSlot.Slot)
                    </td>
                    <td>
                        @if (item.IsLate == true)
                        {
                            <p>LATE</p>
                        }
                        else
                        {
                            <form method="post" asp-controller="Appointment" asp-action="MarkLate">
                                <input type="hidden" name="apptId" value="@item.Id" />
                                <button class="mark-complete-button btn btn-success" type="submit">
                                    Mark Late
                                </button>
                            </form>
                        }
                    </td>
                    <td>
                        @if (item.NoShow == true)
                        {
                            <p>NO SHOW</p>
                        }
                        else
                        {
                            <form method="post" asp-controller="Appointment" asp-action="MarkNoShow">
                                <input type="hidden" name="apptId" value="@item.Id" />
                                <button class="mark-complete-button btn btn-success" type="submit">
                                    Mark No Show
                                </button>
                            </form>
                        }
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-primary">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" href="/Appointment/Index?term=@Model.term&currentPage=@(Model.CurrentPage-1)" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            }
            @for (int i = 1; i < Model.TotalPages; i++)
            {
                if (i == Model.CurrentPage)
                {
                    <li class="page-item"><a class="page-link active" href="/Appointment/Index?@Model.term&currentPage=@i">@i</a></li>
                }
                else
                {
                    <li class="page-item"><a class="page-link" href="/Appointment/Index?@Model.term&currentPage=@i">@i</a></li>
                }
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" href="/Appointment/Index?@Model.term&currentPage=@(Model.CurrentPage+1)" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            }
        </ul>
    </nav>

</div>